name: Deploy FoodWaste Salling

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy locally
      run: |
        export API_KEY=${{ secrets.API_KEY }}
        export BASE_URL=${{ secrets.BASE_URL }}
        cd ~/deploy/update
        ./update_food-waste-salling.sh
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
